substitutions:
  device: boiler
  name: "Chaudière Frisquet"
  reboot_timeout: 14d
  update_interval: 60s
  ota_password: "86d8d705bb585eaf7a68c592a025884c"

esphome:
  name: ${device}

external_components:
  - source: components
  
esp32:
  board: esp32dev
  framework:
    type: arduino

<<: !include common/common.yaml
<<: !include common/text_sensors.yaml
<<: !include common/binary_sensors.yaml
<<: !include common/switches.yaml  
<<: !include common/logger-debug.yaml  

dallas:
  - pin: GPIO26
    
sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml

  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.aqara_salon_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s
        
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.outdoor_temperature
    unit_of_measurement: "°C"
    filters:
      - filter_out: nan
      - heartbeat: 60s

  - platform: dallas
    address: 0xA2032131AB675C28
    name: "boiler_inlet_water_temperature"

  - platform: dallas
    address: 0xAB03213190136128
    name: "boiler_return_water_temperature"

  - platform: heat_curve_climate
    name: "Consigne chaudière"
    type: SETPOINT

climate:
  - platform: heat_curve_climate
    id: boiler_climate
    name: ${name}
    sensor: current_temperature
    outdoor_sensor: outdoor_temperature
    output: boiler_cmd
    control_parameters:
      heat_factor: 1.7
      offset: 20
      kp: 0

output:
  - platform: frisquet_boiler
    id: boiler_cmd
    max_power: 1.0
    min_power: 0
    zero_means_zero: true