substitutions:
  device: gazpar
  name: Gazpar
  reboot_timeout: 14d
  update_interval: 60s
  ota_password: "af24de2740dec1c67371e36d29b8f239"

esphome:
  name: ${device}

esp32:
  board: esp32dev
  framework:
    type: arduino

<<: !include common/common.yaml
<<: !include common/logger.yaml
<<: !include common/text_sensors.yaml
<<: !include common/binary_sensors.yaml
<<: !include common/switches.yaml  

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 57
        minutes: 59
        hours: 23
        then:  
          - pulse_meter.set_total_pulses:
              id: gazpar
              value: 0  
          - lambda: |-
              id(gazpar_puissance_gaz_jour) = 0;

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml

  - platform: homeassistant
    id: grdf_coef
    entity_id: sensor.grdf_coef
    internal: true

  - platform: pulse_meter
    id: gazpar
    pin:
      number: GPIO26
      mode: INPUT_PULLDOWN
    timeout: 20s
    internal_filter: 100ms
    name: "Debit Gazpar TIC"
    unit_of_measurement: "l/mn"
    icon: mdi:fire
    state_class: measurement
    filters:
      - multiply: 10 # 1 impulsion = 10 l

    total:
      unit_of_measurement: "m³"
      name: 'Gazpar Gaz Jour'
      filters:
        - multiply: 0.01 # (pour avoir des m3)
      accuracy_decimals: 3
      icon: mdi:fire
      id: gazpar_gaz_jour
      device_class: "gas"
      state_class: total_increasing
      
  - platform: template
    name: "Gazpar Puissance Gaz Jour"
    lambda: |-
      return id(gazpar_gaz_jour).state * id(grdf_coef).state;
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 3 
    id: gazpar_puissance_gaz_jour
    state_class: total_increasing
